# Window and drawing parameters
WINDOW_NAME = "Evolutionary Cars"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 480
FPS = 60
LINE_WIDTH = 3

# Game settings
GRAVITY = 1000
GROUND_FRICTION = 1
GROUND_HEIGHT = 80
TIMESTEPS = 200

NUM_GENERATIONS = 10
NUM_SURVIVORS = 10
POPULATION_SIZE = 20

# Car properties
CAR_INIT_X = 160
CAR_INIT_Y = GROUND_HEIGHT + 100
CAR_INIT_D = 80

CAR_FRICTION = 1
CAR_MASS = 2
CAR_MOMENTUM = 1

MIN_BODY_PARTS = 3
MAX_BODY_PARTS = 20
MIN_BODY_RADIUS = 10
MAX_BODY_RADIUS = 20

MIN_WHEEL_ANGULAR_VELOCITY = 1
MAX_WHEEL_ANGULAR_VELOCITY = 20
WHEEL_FRICTION = 5
WHEEL_COLLISION_THRES = 0.3

# Colors
BLACK = (0, 0, 0)
GREY = (200, 200, 200)
RED = (1, 0, 0)
GREEN = (0, 1, 0)
BLUE = (25, 25, 200)
